# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-53970105-4'

menu:
- {name: 'About', path: 'menu', url: 'about'}
- {name: 'Writing', path: 'menu', url: 'writing'}
- {name: 'YouTube', path: 'menu', url: 'youtube'}
- {name: 'Contact', path: 'menu', url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/kchromik'}
- {icon: 'youtube', link: 'https://www.youtube.com/channel/UCpATIlZlmRRIN_KunbDrq7A'}
- {icon: 'twitter', link: 'https://twitter.com/kevinchromik'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kevin-chromik-28464897/'}
- {icon: 'envelope', link: 'mailto:hi@kchromik.com'}
- {icon: 'stack-overflow', link: 'https://stackoverflow.com/users/2128765/kchromik'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  previous_page: 'Older'
  next_page: 'Newer'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
